-- MySQL Script generated by MySQL Workbench
-- Thu Oct  1 16:30:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fig_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fig_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fig_1` DEFAULT CHARACTER SET utf8 ;
USE `fig_1` ;

-- -----------------------------------------------------
-- Table `fig_1`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fig_1`.`users` (
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `sure_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fig_1`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fig_1`.`accounts` (
  `account_id` INT NOT NULL,
  `account` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  INDEX `fk_account_users_idx` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
